import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Definición de la fuente Inter con el subset "latin"
const inter = Inter({ subsets: ["latin"] });

// Metadatos de la aplicación
export const metadata: Metadata = {
  title: "Create Next App", // Título de la aplicación
  description: "Generated by create next app", // Descripción de la aplicación
};

// Componente de diseño principal de la aplicación
export default function RootLayout({
  children, // Propiedad para los elementos secundarios
}: Readonly<{
  children: React.ReactNode; // Tipo de los elementos secundarios
}>) {
  return (
    <html lang="en"> {/* Etiqueta html con atributo lang "en" */}
      <body className={inter.className}>{children}</body> {/* Cuerpo con clase de estilo Inter */}
    </html>
  );
}
